function Datainformation = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DATAINFORMATION = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  DATAINFORMATION = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DATAINFORMATION = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Datainformation = importfile("C:\Users\Nici & Luki\Documents\Branching Points\Data_information.xlsx", "Tabelle1", [1, 10]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jun-2020 19:31:17

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 10];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Name", "Mat_Name", "x", "y", "z", "Microscope", "Day"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "categorical", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Name", "Mat_Name"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "Mat_Name", "Microscope"], "EmptyFieldRule", "auto");

% Import the data
Datainformation = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Datainformation = [Datainformation; tb]; %#ok<AGROW>
end

end